import { generateMakefile, normalizePM } from "../main.ts";

function formatValue(value: unknown): string {
  if (typeof value === "string") return value;
  try {
    const json = JSON.stringify(value);
    if (json !== undefined) return json;
  } catch {
    // noop
  }
  return String(value);
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function assertEquals<T>(
  actual: T,
  expected: T,
  message = `Expected ${formatValue(actual)} to equal ${formatValue(expected)}`,
) {
  if (!Object.is(actual, expected)) {
    throw new Error(message);
  }
}

function assertNotEquals<T>(
  actual: T,
  expected: T,
  message = `Expected ${formatValue(actual)} to not equal ${formatValue(expected)}`,
) {
  if (Object.is(actual, expected)) {
    throw new Error(message);
  }
}

function assertStringIncludes(
  actual: string,
  needle: string,
  message = `Expected "${formatValue(actual)}" to include "${needle}"`,
) {
  if (!actual.includes(needle)) {
    throw new Error(message);
  }
}

const SAMPLE_SCRIPTS: Record<string, string> = {
  dev: "next",
  build: "next build",
  start: "next start",
  lint: "next lint",
  "docker:build": "docker build -t offer-generator-ui .",
  "docker:run":
    "docker run -p 3000:3000 --env-file .env.local offer-generator-ui",
  "docker:up": "docker-compose up -d",
  "docker:down": "docker-compose down",
  "docker:logs": "docker-compose logs -f",
  "docker:restart": "docker-compose restart",
  "docker:dev": "docker-compose up --build",
  "docker:dev-with-agent":
    "docker-compose -f docker-compose.full.yml up --build",
  "docker:dev-ui-only":
    "docker-compose -f docker-compose.dev.yml up --build",
  release: "semantic-release",
  changelog: "conventional-changelog -p angular -i CHANGELOG.md -s",
  "version:patch": "pnpm version patch",
  "version:minor": "pnpm version minor",
  "version:major": "pnpm version major",
};

const npmInfo = normalizePM("npm");

function buildMakefile(
  overrides: Record<string, string> = {},
): string {
  return generateMakefile(npmInfo, { ...SAMPLE_SCRIPTS, ...overrides });
}

function targetName(script: string): string {
  return script.replace(/:/g, "-");
}

Deno.test("Generate Makefile from sample package.json", () => {
  const makefile = buildMakefile();
  assertStringIncludes(makefile, "# Auto-generated Makefile — DO NOT EDIT");
  assertStringIncludes(makefile, "PKG_MANAGER := npm");
  assertStringIncludes(makefile, ".PHONY:");
  assertStringIncludes(makefile, "help:");
  assertStringIncludes(makefile, "install:");
  assertStringIncludes(makefile, "ci:");
});

Deno.test("Handle colons in script names", () => {
  const makefile = buildMakefile();
  const colonScripts = Object.keys(SAMPLE_SCRIPTS).filter((name) =>
    name.includes(":")
  );

  for (const script of colonScripts) {
    const target = targetName(script);
    assertStringIncludes(makefile, `${target}:`);
    assertStringIncludes(makefile, `npm run ${script}`);
  }
});

Deno.test("Verify convenience aliases", () => {
  const makefile = buildMakefile();
  assertStringIncludes(makefile, "# alias: s -> start");
  assertStringIncludes(makefile, "s: start");

  assertStringIncludes(makefile, "# alias: d -> dev");
  assertStringIncludes(makefile, "d: dev");

  assertStringIncludes(makefile, "# alias: b -> build");
  assertStringIncludes(makefile, "b: build");

  assertStringIncludes(makefile, "# alias: l -> lint");
  assertStringIncludes(makefile, "l: lint");

  assertStringIncludes(makefile, "# alias: i -> install");
  assertStringIncludes(makefile, "i: install");
});

Deno.test("Verify CI target includes available steps", () => {
  const makefile = buildMakefile();
  assertStringIncludes(makefile, "ci:");
  assertStringIncludes(makefile, "npm run lint");
  assertStringIncludes(makefile, "npm run build");
});

Deno.test("Verify all scripts are included", () => {
  const makefile = buildMakefile();
  for (const script of Object.keys(SAMPLE_SCRIPTS)) {
    const target = targetName(script);
    assertStringIncludes(makefile, `${target}:`);
    assertStringIncludes(makefile, `npm run ${script}`);
  }
});

Deno.test("Verify timestamp changes between runs", async () => {
  const first = buildMakefile();
  await new Promise((resolve) => setTimeout(resolve, 20));
  const second = buildMakefile();

  const firstStamp = first.match(/Generated by js-to-make at (.+)/)?.[1];
  const secondStamp = second.match(/Generated by js-to-make at (.+)/)?.[1];

  assertEquals(typeof firstStamp, "string");
  assertEquals(typeof secondStamp, "string");
  assertNotEquals(firstStamp, secondStamp);
});

Deno.test("Verify version scripts are included", () => {
  const makefile = buildMakefile();
  for (const script of ["version:patch", "version:minor", "version:major"]) {
    const target = targetName(script);
    assertStringIncludes(makefile, `${target}:`);
    assertStringIncludes(makefile, `npm run ${script}`);
  }
});

Deno.test("Verify changelog and release targets", () => {
  const makefile = buildMakefile();
  assertStringIncludes(makefile, "changelog:");
  assertStringIncludes(makefile, "npm run changelog");
  assertStringIncludes(makefile, "release:");
  assertStringIncludes(makefile, "npm run release");
});
